services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: 1234
    #   POSTGRES_DB: payment
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080